# Generated by Django 4.2 on 2025-04-23 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='政府規範類別')),
            ],
        ),
        migrations.CreateModel(
            name='SocialWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='社工姓名')),
                ('staff_id', models.CharField(max_length=20, unique=True, verbose_name='職員編號')),
                ('contact', models.CharField(max_length=50, verbose_name='聯絡方式')),
                ('department', models.CharField(max_length=50, verbose_name='所屬部門')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='活動名稱')),
                ('activity_date', models.DateField(verbose_name='活動日期')),
                ('participant_num', models.IntegerField(verbose_name='參與長者人數')),
                ('total_sessions', models.IntegerField(verbose_name='總節數')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsa.activitycategory', verbose_name='活動類別')),
                ('social_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fsa.socialworker', verbose_name='負責社工')),
            ],
        ),
    ]
